from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional, NotRequired
from langchain_openai import ChatOpenAI
from app.engine.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState

# 导入统一日志系统
from app.utils.logging_init import get_logger
logger = get_logger("default")


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length
    
    # 🆕 新增：多轮辩论结构化状态
    rounds: Annotated[list[dict[str, str]], "Structured debate rounds content (plain text)"]
    bull_report_content: Annotated[str, "Accumulated Bull Report (Markdown)"]
    bear_report_content: Annotated[str, "Accumulated Bear Report (Markdown)"]
    current_round_index: Annotated[int, "Current debate round index (0-based)"]
    max_rounds: Annotated[int, "Max debate rounds (default 2)"]
    latest_speaker: NotRequired[str]  # 最近发言者标识（Bull Researcher / Bear Researcher）


# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Risky Agent's Conversation history"
    ]  # Conversation history
    safe_history: Annotated[
        str, "Safe Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # Last response
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length

    # 多轮辩论结构化状态
    rounds: Annotated[list[dict[str, str]], "Structured debate rounds content"]
    current_round_index: Annotated[int, "Current debate round index (0-based)"]
    max_rounds: Annotated[int, "Max debate rounds (default 3)"]
    risky_report_content: Annotated[str, "Accumulated Risky Report (Markdown)"]
    safe_report_content: Annotated[str, "Accumulated Safe Report (Markdown)"]
    neutral_report_content: Annotated[str, "Accumulated Neutral Report (Markdown)"]


def update_reports(existing: dict, new: dict) -> dict:
    """Reducer for merging reports dictionaries"""
    # 延迟导入以避免循环依赖
    from app.utils.logging_init import get_logger
    local_logger = get_logger("agent_states")
    
    # 记录合并操作
    keys_existing = list(existing.keys()) if existing else []
    keys_new = list(new.keys()) if new else []
    local_logger.info(f"🔄 [Reducer] 合并报告: 现有={keys_existing}, 新增={keys_new}")
    
    if not existing:
        return new
    if not new:
        return existing
    return {**existing, **new}


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step - 核心分析师报告（summary_agent 直接读取）
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # 动态报告字段 - 所有分析师报告通过此 reducer 合并
    reports: Annotated[dict, update_reports]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]

    # 结构化总结字段 (用于前端展示)
    structured_summary: Annotated[dict, "Structured summary for frontend display"]

    # 阶段配置标志 (用于图路由)
    phase2_enabled: Annotated[bool, "Is phase 2 (Debate) enabled"]
    phase3_enabled: Annotated[bool, "Is phase 3 (Risk) enabled"]
    phase4_enabled: Annotated[bool, "Is phase 4 (Trader) enabled — Trader always executes"]
